// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: lbot/proto/orchiestrator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KubeconfigPath   string   `protobuf:"bytes,1,opt,name=KubeconfigPath,proto3" json:"KubeconfigPath,omitempty"`
	Context          string   `protobuf:"bytes,2,opt,name=Context,proto3" json:"Context,omitempty"`
	Namespace        string   `protobuf:"bytes,3,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	HelmTimeout      string   `protobuf:"bytes,4,opt,name=HelmTimeout,proto3" json:"HelmTimeout,omitempty"`
	HelmValuesFiles  []string `protobuf:"bytes,5,rep,name=HelmValuesFiles,proto3" json:"HelmValuesFiles,omitempty"`
	HelmValues       []string `protobuf:"bytes,6,rep,name=HelmValues,proto3" json:"HelmValues,omitempty"`
	HelmFileValues   []string `protobuf:"bytes,7,rep,name=HelmFileValues,proto3" json:"HelmFileValues,omitempty"`
	HelmStringValues []string `protobuf:"bytes,8,rep,name=HelmStringValues,proto3" json:"HelmStringValues,omitempty"`
}

func (x *InstallRequest) Reset() {
	*x = InstallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbot_proto_orchiestrator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallRequest) ProtoMessage() {}

func (x *InstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lbot_proto_orchiestrator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallRequest.ProtoReflect.Descriptor instead.
func (*InstallRequest) Descriptor() ([]byte, []int) {
	return file_lbot_proto_orchiestrator_proto_rawDescGZIP(), []int{0}
}

func (x *InstallRequest) GetKubeconfigPath() string {
	if x != nil {
		return x.KubeconfigPath
	}
	return ""
}

func (x *InstallRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *InstallRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *InstallRequest) GetHelmTimeout() string {
	if x != nil {
		return x.HelmTimeout
	}
	return ""
}

func (x *InstallRequest) GetHelmValuesFiles() []string {
	if x != nil {
		return x.HelmValuesFiles
	}
	return nil
}

func (x *InstallRequest) GetHelmValues() []string {
	if x != nil {
		return x.HelmValues
	}
	return nil
}

func (x *InstallRequest) GetHelmFileValues() []string {
	if x != nil {
		return x.HelmFileValues
	}
	return nil
}

func (x *InstallRequest) GetHelmStringValues() []string {
	if x != nil {
		return x.HelmStringValues
	}
	return nil
}

type InstallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InstallResponse) Reset() {
	*x = InstallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbot_proto_orchiestrator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallResponse) ProtoMessage() {}

func (x *InstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lbot_proto_orchiestrator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallResponse.ProtoReflect.Descriptor instead.
func (*InstallResponse) Descriptor() ([]byte, []int) {
	return file_lbot_proto_orchiestrator_proto_rawDescGZIP(), []int{1}
}

type UnInstallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KubeconfigPath string `protobuf:"bytes,1,opt,name=KubeconfigPath,proto3" json:"KubeconfigPath,omitempty"`
	Context        string `protobuf:"bytes,2,opt,name=Context,proto3" json:"Context,omitempty"`
	Namespace      string `protobuf:"bytes,3,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	HelmTimeout    string `protobuf:"bytes,4,opt,name=HelmTimeout,proto3" json:"HelmTimeout,omitempty"`
}

func (x *UnInstallRequest) Reset() {
	*x = UnInstallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbot_proto_orchiestrator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnInstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnInstallRequest) ProtoMessage() {}

func (x *UnInstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lbot_proto_orchiestrator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnInstallRequest.ProtoReflect.Descriptor instead.
func (*UnInstallRequest) Descriptor() ([]byte, []int) {
	return file_lbot_proto_orchiestrator_proto_rawDescGZIP(), []int{2}
}

func (x *UnInstallRequest) GetKubeconfigPath() string {
	if x != nil {
		return x.KubeconfigPath
	}
	return ""
}

func (x *UnInstallRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *UnInstallRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UnInstallRequest) GetHelmTimeout() string {
	if x != nil {
		return x.HelmTimeout
	}
	return ""
}

type UnInstallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnInstallResponse) Reset() {
	*x = UnInstallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbot_proto_orchiestrator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnInstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnInstallResponse) ProtoMessage() {}

func (x *UnInstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lbot_proto_orchiestrator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnInstallResponse.ProtoReflect.Descriptor instead.
func (*UnInstallResponse) Descriptor() ([]byte, []int) {
	return file_lbot_proto_orchiestrator_proto_rawDescGZIP(), []int{3}
}

var File_lbot_proto_orchiestrator_proto protoreflect.FileDescriptor

var file_lbot_proto_orchiestrator_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6c, 0x62, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x63,
	0x68, 0x69, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0, 0x02, 0x0a, 0x0e, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x4b, 0x75,
	0x62, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x4b, 0x75, 0x62, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x48, 0x65,
	0x6c, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x48, 0x65, 0x6c, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x28, 0x0a, 0x0f,
	0x48, 0x65, 0x6c, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x48, 0x65, 0x6c, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6d, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x48, 0x65, 0x6c, 0x6d,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x48, 0x65, 0x6c, 0x6d, 0x46, 0x69,
	0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e,
	0x48, 0x65, 0x6c, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x2a,
	0x0a, 0x10, 0x48, 0x65, 0x6c, 0x6d, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x48, 0x65, 0x6c, 0x6d, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x94, 0x01,
	0x0a, 0x10, 0x55, 0x6e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x4b, 0x75, 0x62, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4b, 0x75, 0x62, 0x65,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x48, 0x65, 0x6c, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x48, 0x65, 0x6c, 0x6d, 0x54, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x6e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x93, 0x01, 0x0a, 0x13, 0x4f, 0x72,
	0x63, 0x68, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3a, 0x0a, 0x07, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x12, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a,
	0x09, 0x55, 0x6e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x55, 0x6e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x6e, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x08, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_lbot_proto_orchiestrator_proto_rawDescOnce sync.Once
	file_lbot_proto_orchiestrator_proto_rawDescData = file_lbot_proto_orchiestrator_proto_rawDesc
)

func file_lbot_proto_orchiestrator_proto_rawDescGZIP() []byte {
	file_lbot_proto_orchiestrator_proto_rawDescOnce.Do(func() {
		file_lbot_proto_orchiestrator_proto_rawDescData = protoimpl.X.CompressGZIP(file_lbot_proto_orchiestrator_proto_rawDescData)
	})
	return file_lbot_proto_orchiestrator_proto_rawDescData
}

var file_lbot_proto_orchiestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lbot_proto_orchiestrator_proto_goTypes = []interface{}{
	(*InstallRequest)(nil),    // 0: proto.InstallRequest
	(*InstallResponse)(nil),   // 1: proto.InstallResponse
	(*UnInstallRequest)(nil),  // 2: proto.UnInstallRequest
	(*UnInstallResponse)(nil), // 3: proto.UnInstallResponse
}
var file_lbot_proto_orchiestrator_proto_depIdxs = []int32{
	0, // 0: proto.OrchistratorService.Install:input_type -> proto.InstallRequest
	2, // 1: proto.OrchistratorService.UnInstall:input_type -> proto.UnInstallRequest
	1, // 2: proto.OrchistratorService.Install:output_type -> proto.InstallResponse
	3, // 3: proto.OrchistratorService.UnInstall:output_type -> proto.UnInstallResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lbot_proto_orchiestrator_proto_init() }
func file_lbot_proto_orchiestrator_proto_init() {
	if File_lbot_proto_orchiestrator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lbot_proto_orchiestrator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbot_proto_orchiestrator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbot_proto_orchiestrator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnInstallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbot_proto_orchiestrator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnInstallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lbot_proto_orchiestrator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lbot_proto_orchiestrator_proto_goTypes,
		DependencyIndexes: file_lbot_proto_orchiestrator_proto_depIdxs,
		MessageInfos:      file_lbot_proto_orchiestrator_proto_msgTypes,
	}.Build()
	File_lbot_proto_orchiestrator_proto = out.File
	file_lbot_proto_orchiestrator_proto_rawDesc = nil
	file_lbot_proto_orchiestrator_proto_goTypes = nil
	file_lbot_proto_orchiestrator_proto_depIdxs = nil
}
