// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: start.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StartProcess_Run_FullMethodName             = "/proto.StartProcess/Run"
	StartProcess_RunWithProgress_FullMethodName = "/proto.StartProcess/RunWithProgress"
)

// StartProcessClient is the client API for StartProcess service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StartProcessClient interface {
	Run(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	RunWithProgress(ctx context.Context, in *StartWithProgressRequest, opts ...grpc.CallOption) (StartProcess_RunWithProgressClient, error)
}

type startProcessClient struct {
	cc grpc.ClientConnInterface
}

func NewStartProcessClient(cc grpc.ClientConnInterface) StartProcessClient {
	return &startProcessClient{cc}
}

func (c *startProcessClient) Run(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, StartProcess_Run_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *startProcessClient) RunWithProgress(ctx context.Context, in *StartWithProgressRequest, opts ...grpc.CallOption) (StartProcess_RunWithProgressClient, error) {
	stream, err := c.cc.NewStream(ctx, &StartProcess_ServiceDesc.Streams[0], StartProcess_RunWithProgress_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &startProcessRunWithProgressClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StartProcess_RunWithProgressClient interface {
	Recv() (*ProgressResponse, error)
	grpc.ClientStream
}

type startProcessRunWithProgressClient struct {
	grpc.ClientStream
}

func (x *startProcessRunWithProgressClient) Recv() (*ProgressResponse, error) {
	m := new(ProgressResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StartProcessServer is the server API for StartProcess service.
// All implementations must embed UnimplementedStartProcessServer
// for forward compatibility
type StartProcessServer interface {
	Run(context.Context, *StartRequest) (*StartResponse, error)
	RunWithProgress(*StartWithProgressRequest, StartProcess_RunWithProgressServer) error
	mustEmbedUnimplementedStartProcessServer()
}

// UnimplementedStartProcessServer must be embedded to have forward compatible implementations.
type UnimplementedStartProcessServer struct {
}

func (UnimplementedStartProcessServer) Run(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedStartProcessServer) RunWithProgress(*StartWithProgressRequest, StartProcess_RunWithProgressServer) error {
	return status.Errorf(codes.Unimplemented, "method RunWithProgress not implemented")
}
func (UnimplementedStartProcessServer) mustEmbedUnimplementedStartProcessServer() {}

// UnsafeStartProcessServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StartProcessServer will
// result in compilation errors.
type UnsafeStartProcessServer interface {
	mustEmbedUnimplementedStartProcessServer()
}

func RegisterStartProcessServer(s grpc.ServiceRegistrar, srv StartProcessServer) {
	s.RegisterService(&StartProcess_ServiceDesc, srv)
}

func _StartProcess_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StartProcessServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StartProcess_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StartProcessServer).Run(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StartProcess_RunWithProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartWithProgressRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StartProcessServer).RunWithProgress(m, &startProcessRunWithProgressServer{stream})
}

type StartProcess_RunWithProgressServer interface {
	Send(*ProgressResponse) error
	grpc.ServerStream
}

type startProcessRunWithProgressServer struct {
	grpc.ServerStream
}

func (x *startProcessRunWithProgressServer) Send(m *ProgressResponse) error {
	return x.ServerStream.SendMsg(m)
}

// StartProcess_ServiceDesc is the grpc.ServiceDesc for StartProcess service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StartProcess_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StartProcess",
	HandlerType: (*StartProcessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _StartProcess_Run_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunWithProgress",
			Handler:       _StartProcess_RunWithProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "start.proto",
}
