// Code generated by "stringer -type=AgentState -trimprefix=AgentState"; DO NOT EDIT.

package agent

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AgentStateLeader-0]
	_ = x[AgentStateFollower-1]
}

const _AgentState_name = "LeaderFollower"

var _AgentState_index = [...]uint8{0, 6, 14}

func (i AgentState) String() string {
	if i < 0 || i >= AgentState(len(_AgentState_index)-1) {
		return "AgentState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AgentState_name[_AgentState_index[i]:_AgentState_index[i+1]]
}
