{{- if .Values.workload.config -}}
apiVersion: v1
kind: Secret
metadata:
  name: workload-{{ .Values.workload.name }}-secret
  namespace: {{ .Values.workload.namespace }}
data:
  workload-config.json: {{ .Values.workload.config | b64enc | quote }}
{{- end}}
