{{- if .Values.workload.config -}}
apiVersion: v1
kind: Secret
metadata:
  name: workload-{{ .Values.workload.name }}-secret
  namespace: {{ .Values.workload.namespace }}
data:
  workload-config.json: |
{{ toJson .Values.workload.config | indent 4 }}
{{- end}}
