// Code generated by "stringer -type=WorkloadState -trimprefix=WorkloadState"; DO NOT EDIT.

package database

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WorkloadStateCreated-0]
	_ = x[WorkloadStateToRun-1]
	_ = x[WorkloadStateRunning-2]
	_ = x[WorkloadStateDone-3]
	_ = x[WorkloadStateError-4]
	_ = x[WorkloadStateToDelete-5]
	_ = x[WorkloadStateDeleted-6]
}

const _WorkloadState_name = "CreatedToRunRunningDoneErrorToDeleteDeleted"

var _WorkloadState_index = [...]uint8{0, 7, 12, 19, 23, 28, 36, 43}

func (i WorkloadState) String() string {
	if i < 0 || i >= WorkloadState(len(_WorkloadState_index)-1) {
		return "WorkloadState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WorkloadState_name[_WorkloadState_index[i]:_WorkloadState_index[i+1]]
}
